import type { AdvisorSession, AIExecution, Conversation, Message } from "./types";

/**
 * Datos estáticos para maquetar la app de asesor y el dashboard antes de que exista el
 * contrato real de /advisor y /dashboard (F5/F7). Forma = exactamente Conversation/Message
 * de backend/conversations/models.py; nada de campos inventados fuera del modelo.
 */

export const CURRENT_ADVISOR: AdvisorSession = {
  advisor_id: "adv_maria",
  display_name: "María Torres",
};

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    conversation_id: "conv_1001",
    user_type: "AUTHENTICATED",
    status: "PENDING_ADVISOR",
    channel: "WEB",
    bot_enabled: false,
    user_id: "usr_204",
    user_name: "Jorge Salinas",
    user_email: "jorge.salinas@example.com",
    user_company: "Transportes Salinas SAC",
    assigned_advisor_id: null,
    summary: "Pregunta por el estado de su pago tras ganar una subasta de camión Volvo.",
    message_count: 6,
    unread_count: 2,
    last_message_preview: "¿Alguien me puede confirmar si mi pago ya se acreditó?",
    last_message_at: "2026-08-27T14:12:00Z",
    handoff_requested_at: "2026-08-27T14:05:00Z",
    handoff_reason: "faq_no_evidence",
    created_at: "2026-08-20T10:00:00Z",
    updated_at: "2026-08-27T14:12:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_1002",
    user_type: "AUTHENTICATED",
    status: "IN_ATTENTION",
    channel: "WEB",
    bot_enabled: false,
    user_id: "usr_318",
    user_name: "Lucía Ramos",
    user_email: "lucia.ramos@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: "Duda sobre documentación requerida para retirar un vehículo comprado.",
    message_count: 11,
    unread_count: 0,
    last_message_preview: "Perfecto, llevo el DNI y el comprobante mañana. Gracias!",
    last_message_at: "2026-08-27T13:40:00Z",
    handoff_requested_at: "2026-08-27T12:50:00Z",
    handoff_reason: "advisor_request",
    created_at: "2026-07-19T09:12:00Z",
    updated_at: "2026-08-27T13:40:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_1003",
    user_type: "ANONYMOUS",
    status: "BOT_ATTENDING",
    channel: "WEB",
    bot_enabled: true,
    user_id: null,
    user_name: null,
    user_email: null,
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 3,
    unread_count: 0,
    last_message_preview: "¿Qué documentos necesito para registrarme?",
    last_message_at: "2026-08-27T13:58:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-08-27T13:50:00Z",
    updated_at: "2026-08-27T13:58:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_0997",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_115",
    user_name: "Pedro Quispe",
    user_email: "pedro.quispe@example.com",
    user_company: "Quispe E.I.R.L.",
    assigned_advisor_id: "adv_maria",
    summary: "Reclamo por comisión cobrada de más — resuelto, se explicó el cálculo.",
    message_count: 14,
    unread_count: 0,
    last_message_preview: "Ticket cerrado",
    last_message_at: "2026-08-26T18:20:00Z",
    handoff_requested_at: "2026-08-26T17:00:00Z",
    handoff_reason: "advisor_intent",
    created_at: "2026-08-25T11:00:00Z",
    updated_at: "2026-08-26T18:20:00Z",
    closed_at: "2026-08-26T18:20:00Z",
  },
  {
    conversation_id: "conv_1004",
    user_type: "AUTHENTICATED",
    status: "PENDING_ADVISOR",
    channel: "WEB",
    bot_enabled: false,
    user_id: "usr_442",
    user_name: "Carla Núñez",
    user_email: "carla.nunez@example.com",
    user_company: null,
    assigned_advisor_id: null,
    summary: "No encuentra su vehículo pujado en el historial de HERALD.",
    message_count: 4,
    unread_count: 1,
    last_message_preview: "No me aparece la subasta que gané la semana pasada",
    last_message_at: "2026-08-27T11:30:00Z",
    handoff_requested_at: "2026-08-27T11:28:00Z",
    handoff_reason: "faq_no_evidence",
    created_at: "2026-08-27T11:20:00Z",
    updated_at: "2026-08-27T11:30:00Z",
    closed_at: null,
  },
  // ── Ampliación para la vista de negocio (ANALISIS-METRICAS-DASHBOARD.md, Tarea C) ──
  // Los 5 de arriba ya no alcanzan para simular una tendencia — estas 14 reparten fechas en
  // ~9 semanas hacia atrás y cubren los 10 códigos reales de handoff_reason al menos una vez.
  {
    conversation_id: "conv_2001",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_501",
    user_name: "Luis Fernández",
    user_email: "luis.fernandez@example.com",
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 2,
    unread_count: 0,
    last_message_preview: "¿Cómo verifico mi cuenta para poder pujar?",
    last_message_at: "2026-08-24T09:10:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-08-24T09:05:00Z",
    updated_at: "2026-08-24T09:10:00Z",
    closed_at: "2026-08-24T09:10:00Z",
  },
  {
    conversation_id: "conv_2002",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_502",
    user_name: "Rosa Delgado",
    user_email: "rosa.delgado@example.com",
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 2,
    unread_count: 0,
    last_message_preview: "¿Cómo funciona la puja en vivo?",
    last_message_at: "2026-08-22T16:40:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-08-22T16:35:00Z",
    updated_at: "2026-08-22T16:40:00Z",
    closed_at: "2026-08-22T16:40:00Z",
  },
  {
    conversation_id: "conv_2003",
    user_type: "ANONYMOUS",
    status: "BOT_ATTENDING",
    channel: "WEB",
    bot_enabled: true,
    user_id: null,
    user_name: null,
    user_email: null,
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 2,
    unread_count: 0,
    last_message_preview: "¿Tienen alguna Hilux disponible?",
    last_message_at: "2026-08-21T10:00:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-08-21T09:58:00Z",
    updated_at: "2026-08-21T10:00:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_2004",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_503",
    user_name: "Manuel Rojas",
    user_email: "manuel.rojas@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 5,
    unread_count: 0,
    last_message_preview: "Mi transferencia no se refleja en mi saldo",
    last_message_at: "2026-07-19T08:30:00Z",
    handoff_requested_at: "2026-07-19T08:25:00Z",
    handoff_reason: "faq_no_evidence",
    created_at: "2026-07-19T08:15:00Z",
    updated_at: "2026-07-19T08:30:00Z",
    closed_at: "2026-07-19T09:00:00Z",
  },
  {
    conversation_id: "conv_2005",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_504",
    user_name: "Gabriela Soto",
    user_email: "gabriela.soto@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 3,
    unread_count: 0,
    last_message_preview: "Necesito que me llamen, prefiero hablar por teléfono",
    last_message_at: "2026-07-17T14:00:00Z",
    handoff_requested_at: "2026-07-17T13:58:00Z",
    handoff_reason: "voice_channel",
    created_at: "2026-07-17T13:55:00Z",
    updated_at: "2026-07-17T14:00:00Z",
    closed_at: "2026-07-17T14:20:00Z",
  },
  {
    conversation_id: "conv_2006",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_505",
    user_name: "Diego Vargas",
    user_email: "diego.vargas@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 4,
    unread_count: 0,
    last_message_preview: "Voy a poner una queja en el libro de reclamaciones",
    last_message_at: "2026-07-15T11:20:00Z",
    handoff_requested_at: "2026-07-15T11:18:00Z",
    handoff_reason: "legal_threat",
    created_at: "2026-07-15T11:10:00Z",
    updated_at: "2026-07-15T11:20:00Z",
    closed_at: "2026-07-15T12:00:00Z",
  },
  {
    conversation_id: "conv_2007",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_506",
    user_name: "Andrea Chumpitaz",
    user_email: "andrea.chumpitaz@example.com",
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 2,
    unread_count: 0,
    last_message_preview: "¿Qué documentos llevo para el retiro del vehículo?",
    last_message_at: "2026-07-12T15:05:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-07-12T15:00:00Z",
    updated_at: "2026-07-12T15:05:00Z",
    closed_at: "2026-07-12T15:05:00Z",
  },
  {
    conversation_id: "conv_2008",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_507",
    user_name: "Marco Estrada",
    user_email: "marco.estrada@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 6,
    unread_count: 0,
    last_message_preview: "Esto es una estafa, quiero que me expliquen",
    last_message_at: "2026-07-09T10:40:00Z",
    handoff_requested_at: "2026-07-09T10:35:00Z",
    handoff_reason: "fraud_accusation",
    created_at: "2026-07-09T10:20:00Z",
    updated_at: "2026-07-09T10:40:00Z",
    closed_at: "2026-07-09T11:30:00Z",
  },
  {
    conversation_id: "conv_2009",
    user_type: "ANONYMOUS",
    status: "BOT_ATTENDING",
    channel: "WEB",
    bot_enabled: true,
    user_id: null,
    user_name: null,
    user_email: null,
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 1,
    unread_count: 0,
    last_message_preview: "jajaja ok gracias",
    last_message_at: "2026-06-07T19:00:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-06-07T19:00:00Z",
    updated_at: "2026-06-07T19:00:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_2010",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_508",
    user_name: "Vanessa Ibarra",
    user_email: "vanessa.ibarra@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 5,
    unread_count: 0,
    last_message_preview: "Pésimo servicio, ya estoy harta de esto",
    last_message_at: "2026-06-03T13:15:00Z",
    handoff_requested_at: "2026-06-03T13:10:00Z",
    handoff_reason: "hostility",
    created_at: "2026-06-03T13:00:00Z",
    updated_at: "2026-06-03T13:15:00Z",
    closed_at: "2026-06-03T14:00:00Z",
  },
  {
    conversation_id: "conv_2011",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_509",
    user_name: "Renzo Aguilar",
    user_email: "renzo.aguilar@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 4,
    unread_count: 0,
    last_message_preview: "¿Por qué mi pago sigue pendiente después de 3 días?",
    last_message_at: "2026-07-29T09:45:00Z",
    handoff_requested_at: "2026-07-29T09:40:00Z",
    handoff_reason: "faq_no_evidence",
    created_at: "2026-07-29T09:30:00Z",
    updated_at: "2026-07-29T09:45:00Z",
    closed_at: "2026-07-29T10:15:00Z",
  },
  {
    conversation_id: "conv_2012",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_510",
    user_name: "Katherine Ponce",
    user_email: "katherine.ponce@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 3,
    unread_count: 0,
    last_message_preview: "Ya pues, me estás floreando con este bot",
    last_message_at: "2026-07-23T17:30:00Z",
    handoff_requested_at: "2026-07-23T17:28:00Z",
    handoff_reason: "peruvian_complaint",
    created_at: "2026-07-23T17:20:00Z",
    updated_at: "2026-07-23T17:30:00Z",
    closed_at: "2026-07-23T18:00:00Z",
  },
  {
    conversation_id: "conv_2013",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_511",
    user_name: "Julio Cárdenas",
    user_email: "julio.cardenas@example.com",
    user_company: "Cárdenas Transportes",
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 7,
    unread_count: 0,
    last_message_preview: "Quiero que me devuelvan mi plata de la consignación",
    last_message_at: "2026-07-16T12:00:00Z",
    handoff_requested_at: "2026-07-16T11:55:00Z",
    handoff_reason: "funds_claim",
    created_at: "2026-07-16T11:40:00Z",
    updated_at: "2026-07-16T12:00:00Z",
    closed_at: "2026-07-16T13:30:00Z",
  },
  {
    conversation_id: "conv_2014",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_512",
    user_name: "Fiorella Nakamura",
    user_email: "fiorella.nakamura@example.com",
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 2,
    unread_count: 0,
    last_message_preview: "¿Cuánto tarda la devolución a mi billetera?",
    last_message_at: "2026-07-08T10:15:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-07-08T10:10:00Z",
    updated_at: "2026-07-08T10:15:00Z",
    closed_at: "2026-07-08T10:15:00Z",
  },
  {
    conversation_id: "conv_2015",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_513",
    user_name: "Bruno Salazar",
    user_email: "bruno.salazar@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: null,
    message_count: 3,
    unread_count: 0,
    last_message_preview: "No quiero hablar con un bot, quiero un humano",
    last_message_at: "2026-06-30T08:50:00Z",
    handoff_requested_at: "2026-06-30T08:48:00Z",
    handoff_reason: "bot_rejection",
    created_at: "2026-06-30T08:40:00Z",
    updated_at: "2026-06-30T08:50:00Z",
    closed_at: "2026-06-30T09:10:00Z",
  },
];

/**
 * Taxonomía de tipos de ticket — MOCK, D-008 (taxonomía real) sigue abierta. Vive separada de
 * `Conversation` a propósito: ese tipo es espejo exacto del backend y no lleva campos inventados.
 * Solo cubre conversaciones con ticket real (`handoff_requested_at` no nulo) — el anónimo nunca
 * tiene ticket (D-002). Se reemplaza por `problem_type` cuando el backend lo defina.
 */
export const MOCK_TICKET_TYPE: Record<string, string> = {
  conv_1001: "Pagos",
  conv_1002: "Documentación y retiro",
  conv_1004: "Catálogo / HERALD",
  conv_0997: "Reclamos",
};

/**
 * Espejo de `AIUsage` en `develop` (ver `types.ts` y ANALISIS-METRICAS-DASHBOARD.md, Tarea A) —
 * NO existe todavía en esta rama ni hay endpoint que lo agregue entre conversaciones. Una fila
 * por conversación (el real trae varias por conversación — clasificación + respuesta — pero
 * para las métricas agregadas de la Tarea B una basta; simular el pipeline completo no aporta).
 * `topic` en `rag_fragments` es ilustrativo: el Centro de Ayuda real no tiene esta taxonomía
 * documentada todavía, es la misma cautela que ya vale para `MOCK_TICKET_TYPE`.
 */
export const MOCK_AI_EXECUTIONS: AIExecution[] = [
  {
    conversation_id: "conv_1001",
    execution_id: "exec_01",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0021,
    rag_used: true,
    rag_fragments: [{ topic: "pagos", score: 0.6 }],
    created_at: "2026-08-27T14:02:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_1002",
    execution_id: "exec_02",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-08-27T12:50:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_1003",
    execution_id: "exec_03",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0016,
    rag_used: true,
    rag_fragments: [{ topic: "registro", score: 0.9 }],
    created_at: "2026-08-27T13:59:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_0997",
    execution_id: "exec_04",
    intent: "ADVISOR",
    source: "model",
    estimated_cost_usd: 0.0014,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-08-26T17:00:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_1004",
    execution_id: "exec_05",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.002,
    rag_used: true,
    rag_fragments: [{ topic: "historial-compras", score: 0.47 }],
    created_at: "2026-08-27T11:29:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_2001",
    execution_id: "exec_06",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0018,
    rag_used: true,
    rag_fragments: [{ topic: "registro", score: 0.92 }],
    created_at: "2026-08-24T09:07:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_2002",
    execution_id: "exec_07",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0019,
    rag_used: true,
    rag_fragments: [{ topic: "subastas-en-vivo", score: 0.88 }],
    created_at: "2026-08-22T16:37:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_2003",
    execution_id: "exec_08",
    intent: "CATALOG",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-08-21T09:59:00Z",
    billing_month: "2026-08",
  },
  {
    conversation_id: "conv_2004",
    execution_id: "exec_09",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0022,
    rag_used: true,
    rag_fragments: [{ topic: "pagos", score: 0.61 }],
    created_at: "2026-07-19T08:20:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2005",
    execution_id: "exec_10",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-07-17T13:57:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2006",
    execution_id: "exec_11",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-07-15T11:15:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2007",
    execution_id: "exec_12",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.002,
    rag_used: true,
    rag_fragments: [{ topic: "documentos-retiro", score: 0.93 }],
    created_at: "2026-07-12T15:02:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2008",
    execution_id: "exec_13",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-07-09T10:25:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2009",
    execution_id: "exec_14",
    intent: null,
    source: "trivial",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-06-07T19:00:00Z",
    billing_month: "2026-06",
  },
  {
    conversation_id: "conv_2010",
    execution_id: "exec_15",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-06-03T13:08:00Z",
    billing_month: "2026-06",
  },
  {
    conversation_id: "conv_2011",
    execution_id: "exec_16",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0021,
    rag_used: true,
    rag_fragments: [{ topic: "pagos", score: 0.58 }],
    created_at: "2026-07-29T09:35:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2012",
    execution_id: "exec_17",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-07-23T17:25:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2013",
    execution_id: "exec_18",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-07-16T11:50:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2014",
    execution_id: "exec_19",
    intent: "FAQ",
    source: "model",
    estimated_cost_usd: 0.0019,
    rag_used: true,
    rag_fragments: [{ topic: "devoluciones-saldo", score: 0.87 }],
    created_at: "2026-07-08T10:12:00Z",
    billing_month: "2026-07",
  },
  {
    conversation_id: "conv_2015",
    execution_id: "exec_20",
    intent: "ADVISOR",
    source: "rules",
    estimated_cost_usd: 0,
    rag_used: false,
    rag_fragments: [],
    created_at: "2026-06-30T08:45:00Z",
    billing_month: "2026-06",
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  conv_1001: [
    {
      conversation_id: "conv_1001",
      message_id: "msg_1",
      sender_type: "USER",
      sender_id: "usr_204",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "Hola, gané la subasta del camión Volvo pero no veo el pago reflejado.",
      attachment: null,
      created_at: "2026-08-27T14:00:00Z",
    },
    {
      conversation_id: "conv_1001",
      message_id: "msg_2",
      sender_type: "BOT",
      sender_id: null,
      message_type: "TEXT",
      status: "DELIVERED",
      content: "Gracias por escribirnos. Voy a derivarte con un asesor para revisar tu pago.",
      attachment: null,
      created_at: "2026-08-27T14:01:00Z",
    },
    {
      conversation_id: "conv_1001",
      message_id: "msg_3",
      sender_type: "SYSTEM",
      sender_id: null,
      message_type: "SYSTEM",
      status: "DELIVERED",
      content: "HANDOFF_REQUESTED",
      attachment: null,
      created_at: "2026-08-27T14:05:00Z",
    },
    {
      conversation_id: "conv_1001",
      message_id: "msg_4",
      sender_type: "USER",
      sender_id: "usr_204",
      message_type: "TEXT",
      status: "RECEIVED",
      content: "¿Alguien me puede confirmar si mi pago ya se acreditó?",
      attachment: null,
      created_at: "2026-08-27T14:12:00Z",
    },
  ],
  conv_1002: [
    {
      conversation_id: "conv_1002",
      message_id: "msg_10",
      sender_type: "USER",
      sender_id: "usr_318",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "¿Qué documentos necesito para retirar el vehículo?",
      attachment: null,
      created_at: "2026-08-27T12:45:00Z",
    },
    {
      conversation_id: "conv_1002",
      message_id: "msg_11",
      sender_type: "SYSTEM",
      sender_id: null,
      message_type: "SYSTEM",
      status: "DELIVERED",
      content: "ADVISOR_ASSIGNED",
      attachment: null,
      created_at: "2026-08-27T12:51:00Z",
    },
    {
      conversation_id: "conv_1002",
      message_id: "msg_12",
      sender_type: "ADVISOR",
      sender_id: "adv_maria",
      message_type: "TEXT",
      status: "DELIVERED",
      content: "Hola Lucía, necesitas tu DNI y el comprobante de pago. Más info: https://ayuda.vmcsubastas.com/retiro",
      attachment: null,
      created_at: "2026-08-27T13:10:00Z",
    },
    {
      conversation_id: "conv_1002",
      message_id: "msg_13",
      sender_type: "USER",
      sender_id: "usr_318",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "Perfecto, llevo el DNI y el comprobante mañana. Gracias!",
      attachment: null,
      created_at: "2026-08-27T13:40:00Z",
    },
  ],
  conv_1003: [
    {
      conversation_id: "conv_1003",
      message_id: "msg_20",
      sender_type: "USER",
      sender_id: null,
      message_type: "TEXT",
      status: "PROCESSED",
      content: "¿Qué documentos necesito para registrarme?",
      attachment: null,
      created_at: "2026-08-27T13:58:00Z",
    },
  ],
  conv_0997: [
    {
      conversation_id: "conv_0997",
      message_id: "msg_30",
      sender_type: "USER",
      sender_id: "usr_115",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "Me cobraron más comisión de la que esperaba, ¿por qué?",
      attachment: null,
      created_at: "2026-08-26T17:00:00Z",
    },
    {
      conversation_id: "conv_0997",
      message_id: "msg_31",
      sender_type: "ADVISOR",
      sender_id: "adv_maria",
      message_type: "TEXT",
      status: "DELIVERED",
      content: "Hola Pedro, la comisión incluye el fee de intermediación. Te comparto el detalle por correo.",
      attachment: null,
      created_at: "2026-08-26T18:10:00Z",
    },
    {
      conversation_id: "conv_0997",
      message_id: "msg_32",
      sender_type: "SYSTEM",
      sender_id: null,
      message_type: "SYSTEM",
      status: "DELIVERED",
      content: "TICKET_CLOSED",
      attachment: null,
      created_at: "2026-08-26T18:20:00Z",
    },
  ],
  conv_1004: [
    {
      conversation_id: "conv_1004",
      message_id: "msg_40",
      sender_type: "USER",
      sender_id: "usr_442",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "No me aparece la subasta que gané la semana pasada",
      attachment: null,
      created_at: "2026-08-27T11:30:00Z",
    },
    {
      conversation_id: "conv_1004",
      message_id: "msg_41",
      sender_type: "USER",
      sender_id: "usr_442",
      message_type: "IMAGE",
      status: "PROCESSED",
      content: null,
      attachment: { url: "s3://subastin-images/conv_1004/msg_41.jpg", content_type: "image/jpeg" },
      created_at: "2026-08-27T11:31:00Z",
    },
  ],
};
