import type { AdvisorSession, Conversation, Message } from "./types";

/**
 * Datos estáticos para maquetar la app de asesor y el dashboard antes de que exista el
 * contrato real de /advisor y /dashboard (F5/F7). Forma = exactamente Conversation/Message
 * de backend/conversations/models.py; nada de campos inventados fuera del modelo.
 */

export const CURRENT_ADVISOR: AdvisorSession = {
  advisor_id: "adv_maria",
  display_name: "María Torres",
};

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    conversation_id: "conv_1001",
    user_type: "AUTHENTICATED",
    status: "PENDING_ADVISOR",
    channel: "WEB",
    bot_enabled: false,
    user_id: "usr_204",
    user_name: "Jorge Salinas",
    user_email: "jorge.salinas@example.com",
    user_company: "Transportes Salinas SAC",
    assigned_advisor_id: null,
    summary: "Pregunta por el estado de su pago tras ganar una subasta de camión Volvo.",
    message_count: 6,
    unread_count: 2,
    last_message_preview: "¿Alguien me puede confirmar si mi pago ya se acreditó?",
    last_message_at: "2026-08-27T14:12:00Z",
    handoff_requested_at: "2026-08-27T14:05:00Z",
    handoff_reason: "Consulta de pago — requiere validación manual",
    created_at: "2026-08-20T10:00:00Z",
    updated_at: "2026-08-27T14:12:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_1002",
    user_type: "AUTHENTICATED",
    status: "IN_ATTENTION",
    channel: "WEB",
    bot_enabled: false,
    user_id: "usr_318",
    user_name: "Lucía Ramos",
    user_email: "lucia.ramos@example.com",
    user_company: null,
    assigned_advisor_id: "adv_maria",
    summary: "Duda sobre documentación requerida para retirar un vehículo comprado.",
    message_count: 11,
    unread_count: 0,
    last_message_preview: "Perfecto, llevo el DNI y el comprobante mañana. Gracias!",
    last_message_at: "2026-08-27T13:40:00Z",
    handoff_requested_at: "2026-08-27T12:50:00Z",
    handoff_reason: "Solicitud explícita de asesor",
    created_at: "2026-08-19T09:12:00Z",
    updated_at: "2026-08-27T13:40:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_1003",
    user_type: "ANONYMOUS",
    status: "BOT_ATTENDING",
    channel: "WEB",
    bot_enabled: true,
    user_id: null,
    user_name: null,
    user_email: null,
    user_company: null,
    assigned_advisor_id: null,
    summary: null,
    message_count: 3,
    unread_count: 0,
    last_message_preview: "¿Qué documentos necesito para registrarme?",
    last_message_at: "2026-08-27T13:58:00Z",
    handoff_requested_at: null,
    handoff_reason: null,
    created_at: "2026-08-27T13:50:00Z",
    updated_at: "2026-08-27T13:58:00Z",
    closed_at: null,
  },
  {
    conversation_id: "conv_0997",
    user_type: "AUTHENTICATED",
    status: "CLOSED",
    channel: "WEB",
    bot_enabled: true,
    user_id: "usr_115",
    user_name: "Pedro Quispe",
    user_email: "pedro.quispe@example.com",
    user_company: "Quispe E.I.R.L.",
    assigned_advisor_id: "adv_maria",
    summary: "Reclamo por comisión cobrada de más — resuelto, se explicó el cálculo.",
    message_count: 14,
    unread_count: 0,
    last_message_preview: "Ticket cerrado",
    last_message_at: "2026-08-26T18:20:00Z",
    handoff_requested_at: "2026-08-26T17:00:00Z",
    handoff_reason: "Reclamo de comisión",
    created_at: "2026-08-25T11:00:00Z",
    updated_at: "2026-08-26T18:20:00Z",
    closed_at: "2026-08-26T18:20:00Z",
  },
  {
    conversation_id: "conv_1004",
    user_type: "AUTHENTICATED",
    status: "PENDING_ADVISOR",
    channel: "WEB",
    bot_enabled: false,
    user_id: "usr_442",
    user_name: "Carla Núñez",
    user_email: "carla.nunez@example.com",
    user_company: null,
    assigned_advisor_id: null,
    summary: "No encuentra su vehículo pujado en el historial de HERALD.",
    message_count: 4,
    unread_count: 1,
    last_message_preview: "No me aparece la subasta que gané la semana pasada",
    last_message_at: "2026-08-27T11:30:00Z",
    handoff_requested_at: "2026-08-27T11:28:00Z",
    handoff_reason: "Baja confianza de RAG",
    created_at: "2026-08-27T11:20:00Z",
    updated_at: "2026-08-27T11:30:00Z",
    closed_at: null,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  conv_1001: [
    {
      conversation_id: "conv_1001",
      message_id: "msg_1",
      sender_type: "USER",
      sender_id: "usr_204",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "Hola, gané la subasta del camión Volvo pero no veo el pago reflejado.",
      attachment: null,
      created_at: "2026-08-27T14:00:00Z",
    },
    {
      conversation_id: "conv_1001",
      message_id: "msg_2",
      sender_type: "BOT",
      sender_id: null,
      message_type: "TEXT",
      status: "DELIVERED",
      content: "Gracias por escribirnos. Voy a derivarte con un asesor para revisar tu pago.",
      attachment: null,
      created_at: "2026-08-27T14:01:00Z",
    },
    {
      conversation_id: "conv_1001",
      message_id: "msg_3",
      sender_type: "SYSTEM",
      sender_id: null,
      message_type: "SYSTEM",
      status: "DELIVERED",
      content: "HANDOFF_REQUESTED",
      attachment: null,
      created_at: "2026-08-27T14:05:00Z",
    },
    {
      conversation_id: "conv_1001",
      message_id: "msg_4",
      sender_type: "USER",
      sender_id: "usr_204",
      message_type: "TEXT",
      status: "RECEIVED",
      content: "¿Alguien me puede confirmar si mi pago ya se acreditó?",
      attachment: null,
      created_at: "2026-08-27T14:12:00Z",
    },
  ],
  conv_1002: [
    {
      conversation_id: "conv_1002",
      message_id: "msg_10",
      sender_type: "USER",
      sender_id: "usr_318",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "¿Qué documentos necesito para retirar el vehículo?",
      attachment: null,
      created_at: "2026-08-27T12:45:00Z",
    },
    {
      conversation_id: "conv_1002",
      message_id: "msg_11",
      sender_type: "SYSTEM",
      sender_id: null,
      message_type: "SYSTEM",
      status: "DELIVERED",
      content: "ADVISOR_ASSIGNED",
      attachment: null,
      created_at: "2026-08-27T12:51:00Z",
    },
    {
      conversation_id: "conv_1002",
      message_id: "msg_12",
      sender_type: "ADVISOR",
      sender_id: "adv_maria",
      message_type: "TEXT",
      status: "DELIVERED",
      content: "Hola Lucía, necesitas tu DNI y el comprobante de pago. Más info: https://ayuda.vmcsubastas.com/retiro",
      attachment: null,
      created_at: "2026-08-27T13:10:00Z",
    },
    {
      conversation_id: "conv_1002",
      message_id: "msg_13",
      sender_type: "USER",
      sender_id: "usr_318",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "Perfecto, llevo el DNI y el comprobante mañana. Gracias!",
      attachment: null,
      created_at: "2026-08-27T13:40:00Z",
    },
  ],
  conv_1003: [
    {
      conversation_id: "conv_1003",
      message_id: "msg_20",
      sender_type: "USER",
      sender_id: null,
      message_type: "TEXT",
      status: "PROCESSED",
      content: "¿Qué documentos necesito para registrarme?",
      attachment: null,
      created_at: "2026-08-27T13:58:00Z",
    },
  ],
  conv_0997: [
    {
      conversation_id: "conv_0997",
      message_id: "msg_30",
      sender_type: "USER",
      sender_id: "usr_115",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "Me cobraron más comisión de la que esperaba, ¿por qué?",
      attachment: null,
      created_at: "2026-08-26T17:00:00Z",
    },
    {
      conversation_id: "conv_0997",
      message_id: "msg_31",
      sender_type: "ADVISOR",
      sender_id: "adv_maria",
      message_type: "TEXT",
      status: "DELIVERED",
      content: "Hola Pedro, la comisión incluye el fee de intermediación. Te comparto el detalle por correo.",
      attachment: null,
      created_at: "2026-08-26T18:10:00Z",
    },
    {
      conversation_id: "conv_0997",
      message_id: "msg_32",
      sender_type: "SYSTEM",
      sender_id: null,
      message_type: "SYSTEM",
      status: "DELIVERED",
      content: "TICKET_CLOSED",
      attachment: null,
      created_at: "2026-08-26T18:20:00Z",
    },
  ],
  conv_1004: [
    {
      conversation_id: "conv_1004",
      message_id: "msg_40",
      sender_type: "USER",
      sender_id: "usr_442",
      message_type: "TEXT",
      status: "PROCESSED",
      content: "No me aparece la subasta que gané la semana pasada",
      attachment: null,
      created_at: "2026-08-27T11:30:00Z",
    },
    {
      conversation_id: "conv_1004",
      message_id: "msg_41",
      sender_type: "USER",
      sender_id: "usr_442",
      message_type: "IMAGE",
      status: "PROCESSED",
      content: null,
      attachment: { url: "s3://subastin-images/conv_1004/msg_41.jpg", content_type: "image/jpeg" },
      created_at: "2026-08-27T11:31:00Z",
    },
  ],
};
